In [3]:
import numpy as np

In [11]:
list = [0,1,2,3,4,5,6,7,8]

In [17]:
calculations = np.array(list)

In [18]:
print(calculations)

[0 1 2 3 4 5 6 7 8]


In [20]:
calculations = calculations.reshape(3,3)

In [81]:
print(ls.mean(axis=0))

[3. 4. 5.]


In [43]:
for i in calculations:
  print(i.mean())
  print(i.var())

1.0
0.6666666666666666
4.0
0.6666666666666666
7.0
0.6666666666666666


In [45]:
for i in calculations.T:
  print(i.mean())
  print(i.var())
  print(i.std())


3.0
6.0
2.449489742783178
4.0
6.0
2.449489742783178
5.0
6.0
2.449489742783178


In [48]:
print(calculations.mean(axis=0))

[3. 4. 5.]


In [88]:
ls = np.array(list).reshape(3,3)
calculations = {
      'mean': [ ls.mean( axis=0 ).tolist() , ls.mean( axis=1 ).tolist(), ls.mean() ],
      'variance': [ ls.var( axis=0 ).tolist(), ls.var( axis=1 ).tolist(), ls.var() ],
      'standard deviation': [ ls.std( axis=0 ).tolist(), ls.std(axis=1).tolist(), ls.std() ],
      'max': [ ls.max( axis=0 ).tolist(), ls.max( axis=1 ).tolist(), ls.max() ],
      'min': [ ls.min( axis=0 ).tolist(), ls.min( axis=1 ).tolist(), ls.min() ],
      'sum': [ ls.sum( axis = 0 ).tolist(), ls.sum( axis = 1 ).tolist(), ls.sum() ]
    }
print(calculations)

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}


In [86]:
print(type(ls.mean( axis=0 ).tolist()))

<class 'list'>


In [82]:
print(ls.view())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
