> # <center>Mean-Variance-Standard Deviation Calculator</center>
> 
> You will be <u>[working on this project with our Replit starter code.](https://replit.com/github/freeCodeCamp/boilerplate-mean-variance-standard-deviation-calculator)</u>
> 
> - Start by importing the project on Replit.
> - Next, you will see a `.replit` window.
> - Select `Use run command` and click the `Done` button.
> 
> We are still developing the interactive instructional part of the Python curriculum. For now, here are some videos on the freeCodeCamp.org YouTube channel that will teach you everything you need to know to complete this project:
> 
> - [Python for Everybody Video Course (14 hours)](https://www.freecodecamp.org/news/python-for-everybody/)
> 
> - [How to Analyze Data with Python Pandas (10 hours)](https://www.freecodecamp.org/news/how-to-analyze-data-with-python-pandas/)
> 
> Create a function named `calculate()` in `mean_var_std.py` that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.
> 
> The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.
> 
> The returned dictionary should follow this format:
> 
> ```Python {
>    'mean': [axis1, axis2, flattened],
>    'variance': [axis1, axis2, flattened],
>    'standard deviation': [axis1, axis2, flattened],
>    'max': [axis1, axis2, flattened],
>    'min': [axis1, axis2, flattened],
>    'sum': [axis1, axis2, flattened]
>  }
> ```
> If a list containing less than 9 elements is passed into the function, it should raise a ValueError exception with the message: "List must contain nine numbers." The values in the returned dictionary should be lists and not Numpy arrays.
> 
> For example, `calculate([0,1,2,3,4,5,6,7,8])` should return:
> ```Python
> {
>   'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
>   'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
>   'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
>   'max': [[6, 7, 8], [2, 5, 8], 8],
>   'min': [[0, 1, 2], [0, 3, 6], 0],
>   'sum': [[9, 12, 15], [3, 12, 21], 36]
> } 
> ```
> The unit tests for this project are in `test_module.py`.
> 
> #### Development
> For development, you can use `main.py` to test your `calculate()` function. Click the "run" button and `main.py` will run.
> 
> #### Testing
> We imported the tests from `test_module.py` to `main.py` for your convenience. The tests will run automatically whenever you hit the "run" button.
> 
> #### Submitting
> Copy your project's URL and submit it to freeCodeCamp.

### Imports
---

In [1]:
import numpy as np

### Create and reshape the list from the example
---

In [2]:
list = [0,1,2,3,4,5,6,7,8]

In [7]:
calculations = np.array(list).reshape(3,3)

In [8]:
print(calculations)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
for i in calculations:
  print(i.mean())
  print(i.var())

1.0
0.6666666666666666
4.0
0.6666666666666666
7.0
0.6666666666666666


In [10]:
for i in calculations.T:
  print(i.mean())
  print(i.var())
  print(i.std())


3.0
6.0
2.449489742783178
4.0
6.0
2.449489742783178
5.0
6.0
2.449489742783178


In [ ]:
print(calculations.mean(axis=0))

[3. 4. 5.]


### Format the output as an object
---

In [18]:
ls = np.array(list).reshape(3,3)
calculations = {
      'mean': [ ls.mean( axis=0 ).tolist() , ls.mean( axis=1 ).tolist(), ls.mean() ],
      'variance': [ ls.var( axis=0 ).tolist(), ls.var( axis=1 ).tolist(), ls.var() ],
      'standard deviation': [ ls.std( axis=0 ).tolist(), ls.std(axis=1).tolist(), ls.std() ],
      'max': [ ls.max( axis=0 ).tolist(), ls.max( axis=1 ).tolist(), ls.max() ],
      'min': [ ls.min( axis=0 ).tolist(), ls.min( axis=1 ).tolist(), ls.min() ],
      'sum': [ ls.sum( axis = 0 ).tolist(), ls.sum( axis = 1 ).tolist(), ls.sum() ]
    }


for c in calculations :
  print( c, calculations[c] )

mean [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0]
variance [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667]
standard deviation [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611]
max [[6, 7, 8], [2, 5, 8], 8]
min [[0, 1, 2], [0, 3, 6], 0]
sum [[9, 12, 15], [3, 12, 21], 36]


In [14]:
ls.mean( axis=0 ).tolist()

[3.0, 4.0, 5.0]

In [13]:
print(ls.view())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
