In [3]:
import numpy as np

In [11]:
list = [0,1,2,3,4,5,6,7,8]

In [17]:
calculations = np.array(list)

In [18]:
print(calculations)

[0 1 2 3 4 5 6 7 8]


In [20]:
calculations = calculations.reshape(3,3)

In [43]:
for i in calculations:
  print(i.mean())
  print(i.var())

1.0
0.6666666666666666
4.0
0.6666666666666666
7.0
0.6666666666666666


In [45]:
for i in calculations.T:
  print(i.mean())
  print(i.var())
  print(i.std())


3.0
6.0
2.449489742783178
4.0
6.0
2.449489742783178
5.0
6.0
2.449489742783178


In [48]:
print(calculations.mean(axis=0))

[3. 4. 5.]


In [60]:
ls = np.array(list).reshape(3,3)
calculations = {
      'mean': [ ls.mean( axis=0 ), ls.mean( axis=1 ), ls.mean() ],
      'variance': [ ls.var( axis=0 ), ls.var( axis=1 ), ls.var() ],
      'standard deviation': [ ls.std( axis=0 ), ls.var(axis=1), ls.var() ],
      'max': [ ls.max( axis=0 ), ls.max( axis=1 ), ls.max() ],
      'min': [ ls.min( axis=0 ), ls.min( axis=1 ), ls.min() ],
      'sum': [ ls.sum( axis = 0 ), ls.sum( axis = 1 ), ls.sum() ]
    }
print(calculations)

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0], 'variance': [array([6., 6., 6.]), array([0.66666667, 0.66666667, 0.66666667]), 6.666666666666667], 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]), array([0.66666667, 0.66666667, 0.66666667]), 6.666666666666667], 'max': [array([6, 7, 8]), array([2, 5, 8]), 8], 'min': [array([0, 1, 2]), array([0, 3, 6]), 0], 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}


In [53]:
print(ls.mean( axis=0 ))

[3. 4. 5.]


In [59]:
print(ls.view())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
